DotNet.SSO.Portal/Areas/Manager/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DotNet.SSO.Model;

namespace DotNet.SSO.Portal.Areas.Manager.Controllers
{
    public class CommonController : Controller
    {

        #region 顶部导航加头部
        //顶部导航
        [ChildActionOnly]
        [HttpGet]
        public ActionResult TopNav()
        {
            return PartialView();
        } 
        #endregion

        #region 头部导航
        [ChildActionOnly]
        [HttpGet]
        public ActionResult TopHeader()
        {
            ViewBag.CurrentManager = new DotNet.SSO.Model.Manager()
            {
                LoginName="测试帐号",
                ManagerId=1
            };
            return PartialView();
        } 
        #endregion


        #region 加载左侧
        [HttpGet]
        public ActionResult LoadLeft()
        {
            int menuId = DotNet.Utils.Untility.ConvertFactory.ToInt32(Request["menuId"], 0);
            if (menuId == 1)
            {
                WebMenu menu1 = new WebMenu()
                {
                    Id = 1,
                    MenuName = "单点登录配置",
                    Level = 1,
                    ParentMenuId = 0,
                    SubMenus = new List<WebMenu>()
                    {
                        new WebMenu(){ Id=11,MenuName="单点登录池管理",Level=2,ParentMenuId=1,Url="/Manager/SSOPool/SSOPoolList"},
                        new WebMenu(){ Id=12,MenuName="域管理",Level=2,ParentMenuId=1,Url="/Manager/Domain/DomainList"}
                    }
                };
                //WebMenu menu3 = new WebMenu()
                //{
                //    Id = 33,
                //    MenuName = "测试",
                //    Level = 1,
                //    ParentMenuId = 0,
                //    SubMenus = new List<WebMenu>()
                //    {
                //        new WebMenu(){ Id=3,MenuName="测试",Level=2,ParentMenuId=1,Url="/Manager/ttt/ttt1"},
                //        new WebMenu(){ Id=4,MenuName="测试",Level=2,ParentMenuId=1,Url="/Manager/ttt/ttt2"}
                //    }
                //};
                List<WebMenu> menuList1 = new List<WebMenu>();
                menuList1.Add(menu1);
                //menuList1.Add(menu3);
                return Json(menuList1,JsonRequestBehavior.AllowGet);
            }
            else if (menuId == 2)
            {
                WebMenu menu2 = new WebMenu()
                {
                    Id = 2,
                    MenuName = "用户帐号配置",
                    Level = 1,
                    ParentMenuId = 0,
                    SubMenus = new List<WebMenu>()
                    {
                        new WebMenu(){ Id=21,MenuName="帐号管理",Level=2,ParentMenuId=2,Url="/Manager/Account/AccountList"}
                    }
                };
                List<WebMenu> menuList2 = new List<WebMenu>();
                menuList2.Add(menu2);
                return Json(menuList2, JsonRequestBehavior.AllowGet);
            }
            return Json("", JsonRequestBehavior.AllowGet);

        } 
        #endregion



    }
}

DotNet.SSO.Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

DotNet.SSO.Portal/Views/Shared/_LayoutAdd.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/css/base")
    @RenderSection("css", required: false)
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
	      <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
	    <![endif]-->
</head>
<body>
    @RenderBody()
</body>
</html>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/common")
@Scripts.Render("~/bundles/jqueryval")
@RenderSection("scripts", required: false)

DotNet.SSO.Portal/Views/Shared/_LayoutDisplay.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/css/base")
    @RenderSection("css", required: false)
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
	      <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
	    <![endif]-->
</head>
<body>
    @RenderBody()
</body>
</html>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/common")
@Scripts.Render("~/bundles/jqueryval")
@RenderSection("scripts", required: false)

DotNet.SSO.Portal/Views/Shared/_LayoutEdit.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/css/base")
    @RenderSection("css", required: false)
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
	      <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
	    <![endif]-->
</head>
<body>
    @RenderBody()
</body>
</html>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/common")
@Scripts.Render("~/bundles/jqueryval")
@RenderSection("scripts", required: false)

DotNet.SSO.Portal/Views/Shared/_LayoutList.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta content="" charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/css/base")
    @RenderSection("css", required: false)
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
	      <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
	    <![endif]-->
</head>
<body>
        @RenderBody()
</body>
</html>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/common")
@RenderSection("scripts", required: false)
@*<script src="@Url.Content("~/Content/js/user_list.js")" type="text/javascript"></script>
*@

DotNet.SSO.Portal/Views/Shared/_LayoutMain.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta content="" charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/css/base")
    @RenderSection("css", required: false)
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
	      <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
	    <![endif]-->
</head>
<body>
    @Html.Action("TopHeader", "Common", new { Area = "Manager" })
    @Html.Action("TopNav", "Common", new { Area = "Manager" })
    <!--左侧导航列表-->
    <div class="main">
        <!--左侧导航列表-->
        <div class="left_nav" id="if_url">
            <ul>
            </ul>
        </div>
        <!--右侧框架-->
        @*    <div class="centercontent">
            <iframe src="" id="iframeleft" name="iframeleft"></iframe>
        </div>*@
        <div class="centercontent">
            <!--tab libox-->
            <div class="bq_nav" id="ifr_libox">
            </div>
            <!--iframe box-->
            <div id="iframeleft">
            </div>
        </div>
    </div>
    @RenderBody()
</body>
</html>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/common")
@RenderSection("scripts", required: false)
@*@section scripts{
    <script type="text/javascript">
        $(function () {
            $("#user_cash_index").addClass("action");
            $("#cash_recharge").addClass("active");
        });
    </script>
}*@ 