DotNet.SSO.Portal/Areas/Manager/Controllers/SSOPoolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DotNet.SSO.IBll;
using DotNet.SSO.Bll;
using DotNet.SSO.Model.Parameter;
using DotNet.SSO.Model.ViewModel;
using DotNet.SSO.Model.Enum;
using System.Threading;
using DotNet.SSO.Model;
using DotNet.SSO.Portal.CustomsAttribute;

namespace DotNet.SSO.Portal.Areas.Manager.Controllers
{
    public class SSOPoolController : Controller
    {


        // GET: /Manager/SSOPool/SSOPoolList
        #region 单点登录池展示页面
        [HttpGet]
        [ValidateInput(false)]
        public ActionResult SSOPoolList()
        {
           
            List<SelectListItem> selectItem = new List<SelectListItem>()
            {
                new SelectListItem(){ Text="全部",Value="0",Selected=true },
                new SelectListItem(){ Text="已启用",Value=((int)Model.Enum.IsEnabledEnum.Enabled).ToString() },
                new SelectListItem(){ Text="未启用",Value=((int)Model.Enum.IsEnabledEnum.Disabled).ToString() }
            };
            ViewBag.Select = selectItem;
            ISSOPoolService service = new SSOPoolService();
            SSOPoolParam parameter = new SSOPoolParam()
            {
                PageIndex = DotNet.Utils.Untility.ConvertFactory.ToInt32(HttpUtility.UrlEncode(Request["page"]), 1),
                PageSize =12,
                IsEnabled = DotNet.Utils.Untility.ConvertFactory.ToInt32(HttpUtility.UrlEncode(Request["isEnabled"]), 0),
                PoolName = HttpUtility.HtmlEncode(Request["poolName"]),
                IsPaging = true,
                PoolId = 0
            };
            var model = service.GetPagingModel(parameter);
            return View(model);
        } 
        #endregion

        // HttpPost: /Manager/SSOPool/SSOPoolSearch
        #region 单点登录池搜索
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult SSOPoolSearch()
        {
            string poolName = HttpUtility.HtmlEncode(Request["poolName"]);
            string isEnabled = HttpUtility.HtmlEncode(Request["isEnabled"]);
            return Redirect(string.Format("/Manager/SSOPool/SSOPoolList?poolName={0}&isEnabled={1}", poolName, isEnabled));
        } 
        #endregion

        // Get: /Manager/SSOPool/SSOPoolAdd
        #region 添加单点登录池
        [HttpGet]
        public ActionResult SSOPoolAdd()
        {
            return View();
        }
       
        //提交
        [HttpPost]
        public ActionResult SSOPoolAdd(SSOPoolAddModel addModel)
        {
            ISSOPoolService service = new SSOPoolService();
            var jsonModel = service.AddSSOPool(addModel);
            if (jsonModel.Success)
            {
                return Json(new { success = true, msg = "添加成功" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, msg = jsonModel.ErrMsg }, JsonRequestBehavior.AllowGet);
            }
        } 
        #endregion

        // POST: /Manager/SSOPool/SSOPoolDelete
        #region 删除单点登录池
        [HttpPost]
        public ActionResult SSOPoolDelete(int id)
        {
            ISSOPoolService service = new SSOPoolService();
            var jsonModel = service.DeleteSSOPool(id);
            if (jsonModel.Success)
            {
                return Json(new { success = true, msg = "删除成功" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, msg = jsonModel.ErrMsg }, JsonRequestBehavior.AllowGet);
            }
        } 
        #endregion

        // POST: /Manager/SSOPool/ChangePoolEnabled
        #region 开始或者关闭池子
        [HttpPost]
        public ActionResult ChangePoolEnabled()
        {
            int poolId = DotNet.Utils.Untility.ConvertFactory.ToInt32(HttpUtility.HtmlEncode(Request["poolId"]),0);
            int isEnabled = DotNet.Utils.Untility.ConvertFactory.ToInt32(HttpUtility.HtmlEncode(Request["isEnabled"]),(int)IsEnabledEnum.Enabled);
            ISSOPoolService service = new SSOPoolService();
            var jsonModel = service.ChangeSSOPoolEnabled(poolId,isEnabled);
            if (jsonModel.Success)
            {
                return Json(new { success=true,msg="操作成功" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = true, msg = jsonModel.ErrMsg }, JsonRequestBehavior.AllowGet);
            }
        } 
        #endregion

        // GET: /Manager/SSOPool/SSOPoolEdit
        #region 修改单点登录池
        [HttpGet]
        public ActionResult SSOPoolEdit(int poolId)
        {
            ISSOPoolService service = new SSOPoolService();
            var model = service.GetEditModel(poolId);
            //主要的域名验证的 select
            List<SelectListItem> domainSelectList = new List<SelectListItem>();
            IDomainService domainService = new DomainService();
            var domainList = domainService.GetPoolDomain(poolId);
            domainSelectList.Add(new SelectListItem()
            {
                Text="无",
                Value="0",
                Selected=(model.MainDomainId==0)
            });
            foreach (var domain in domainList)
            {
                SelectListItem item = new SelectListItem()
                {
                    Text=domain.DomainName,
                    Value=domain.DomainId.ToString(),
                    Selected=(domain.DomainId==model.MainDomainId)
                };
                domainSelectList.Add(item);
            }
            this.ViewData["MainDomainId"] = domainSelectList.AsEnumerable();
            return View(model);
        }
        //修改单点登录池提交
        [HttpPost]
        public ActionResult SSOPoolEdit(SSOPoolEditModel editModel)
        {
            ISSOPoolService service = new SSOPoolService();
            var jsonModel = service.EditSSOPool(editModel);
            if (jsonModel.Success)
            {
                return Json(new { success = true, msg = "修改成功" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, msg = jsonModel.ErrMsg }, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

        //GET :/Manager/SSOPool/SSOPoolDisplay
        #region 显示单点登录池的详情
        [HttpGet]
        public ActionResult SSOPoolDisplay(int poolId)
        {
            ISSOPoolService service = new SSOPoolService();
            var displayModel = service.GetDisplayModel(poolId);

            return View(displayModel);
        } 
        #endregion
    }
}

DotNet.SSO.Portal/Areas/Manager/Views/SSOPool/SSOPoolAdd.cshtml
@{
    ViewBag.Title = "添加单点登录池";
    Layout = "~/Views/Shared/_LayoutAdd.cshtml";
}
@model DotNet.SSO.Model.ViewModel.SSOPoolAddModel
<div class="listbox">
    <div class="pagetitle">
        添加单点登录池 <a href="@Url.Content("/Manager/SSOPool/SSOPoolList")">>>返回列表</a>
    </div>
    @using (Ajax.BeginForm("SSOPoolAdd", "SSOPool", new { }, new AjaxOptions() { HttpMethod = "Post", OnBegin = "startLoading('正在加载')", OnSuccess = "AfterPoolAdd" }, new { id = "SSOPoolAdd" }))
    { 
        <table class="table table-bordered table-condensed">
            <tr>
                <td colspan="2">
                    添加单点登录池
                </td>
            </tr>
            <tr>
                <td class="item_title">
                    登录池名称:
                </td>
                <td class="item_input">
                @Html.TextBoxFor(model => model.PoolName, new { @class = "form-control input-sm", @placeholder = "登录池名称" })
                @Html.ValidationMessageFor(model=>model.PoolName)
                </td>
            </tr>
            <tr>
                <td class="item_title">
                    最大域的数量:
                </td>
                <td class="item_input">
                    @Html.TextBoxFor(model => model.MaxAmount, new { @class = "form-control input-sm", @placeholder = "最大域的数量" })
                    @Html.ValidationMessageFor(model=>model.MaxAmount)
                </td>
            </tr>
               <tr>
                <td class="item_title">
                    是否启用:
                </td>
                <td class="item_input">
                    <input name="IsEnabled" id="Radio1" type="radio" value="@((int)DotNet.SSO.Model.Enum.IsEnabledEnum.Enabled)" checked=checked />启用
                    <input name="IsEnabled" id="Radio2" type="radio"  value="@((int)DotNet.SSO.Model.Enum.IsEnabledEnum.Disabled)" />禁用
                    @Html.ValidationMessageFor(model=>model.MaxAmount)
                </td>
            </tr>

            <tr>
                <td class="item_title">
                    备注:
                </td>
                <td class="item_input">
                  @Html.TextAreaFor(model => model.ReMark, new { @rows = 3, @class = "form-control", @placeholder="备注" })
               @*   @Html.ValidationMessageFor(model=>model.ReMark)*@
                </td>
            </tr>

            <tr>
                <td colspan="2">
                    &nbsp;
                </td>
            </tr>
            <tr>
                <td class="item_title">
                </td>
                <td class="item_input">
                    <button type="submit" class="btn btn-primary btn-sm" style="width: 150px;">
                        保存</button>
                </td>
            </tr>
        </table>
    }
</div>
@section scripts{
 <script type="text/javascript" src="@Url.Content("~/Content/js/ssopool.js")"></script>
}

DotNet.SSO.Portal/Areas/Manager/Views/SSOPool/SSOPoolDisplay.cshtml
@model DotNet.SSO.Model.SSOPoolDisplayModel
@{
    ViewBag.Title = "单点登录池详情";
    Layout = "~/Views/Shared/_LayoutDisplay.cshtml";
}
<div class="listbox">
    <div class="pagetitle">
        单点登录池 <a href="@Url.Content("/Manager/SSOPool/SSOPoolList")">>>返回列表</a>
    </div>
    <table class="table table-bordered table-condensed">
        <tr>
            <td colspan="2">
                单点登录池详情
            </td>
        </tr>
        <tr>
            <td class="item_title">
                登录池名称:
            </td>
            <td class="item_input">
                @Model.PoolName
            </td>
        </tr>
        <tr>
            <td class="item_title">
                是否启用:
            </td>
            <td class="item_input">
                @if (Model.IsEnabled == (int)DotNet.SSO.Model.Enum.IsEnabledEnum.Enabled)
                {
                    <span>启用</span> 
                }
                else
                { 
                    <span>禁用</span> 
                }
            </td>
        </tr>
        <tr>
            <td class="item_title">
                最大域数量:
            </td>
            <td class="item_input">
                @Model.MaxAmount
            </td>
        </tr>
        <tr>
            <td class="item_title">
                当前域数量:
            </td>
            <td class="item_input">
                @Model.CurrentDomainCount
            </td>
        </tr>
            <tr>
            <td class="item_title">
                登录池中的域:
            </td>
            <td class="item_input">
               @{
                   foreach (var item in Model.Domains)
                   { 
                       <a href="@Url.Content(string.Format("/Manager/Domain/DomainDisplay?domainId={0}",item.DomainId))" >@item.DomainName</a>
                   }
               }
            </td>
        </tr>
        <tr>
            <td class="item_title">
                备注:
            </td>
            <td class="item_input">
                @Model.ReMark
            </td>
        </tr>
    </table>
</div>
@section scripts{
    <script type="text/javascript" src="@Url.Content("~/Content/js/ssopool.js")"></script>
}

DotNet.SSO.Portal/Areas/Manager/Views/SSOPool/SSOPoolEdit.cshtml
@model DotNet.SSO.Model.ViewModel.SSOPoolEditModel
@{
    ViewBag.Title = "修改单点登录池";
    Layout = "~/Views/Shared/_LayoutEdit.cshtml";
}
<div class="listbox">
    <div class="pagetitle">
        修改单点登录池 <a href="@Url.Content("/Manager/SSOPool/SSOPoolList")">>>返回列表</a>
    </div>
    @using (Ajax.BeginForm("SSOPoolEdit", "SSOPool", new { }, new AjaxOptions() { HttpMethod = "Post", OnBegin = "startLoading('正在提交')", OnSuccess = "AfterPoolEdit" }, new { id = "SSOPoolEdit" }))
    { 
        @Html.HiddenFor(model=>model.PoolId)
        <table class="table table-bordered table-condensed">
            <tr>
                <td colspan="2">
                    修改单点登录池
                </td>
            </tr>
            <tr>
                <td class="item_title">
                    登录池名称:
                </td>
                <td class="item_input">
                    @Html.TextBoxFor(model => model.PoolName, new { @class = "form-control input-sm", @placeholder = "登录池名称" })
                    @Html.ValidationMessageFor(model => model.PoolName)
                </td>
            </tr>
            <tr>
                <td class="item_title">
                    最大域的数量:
                </td>
                <td class="item_input">
                    @Html.TextBoxFor(model => model.MaxAmount, new { @class = "form-control input-sm", @placeholder = "最大域的数量" })
                    @Html.ValidationMessageFor(model => model.MaxAmount)
                </td>
            </tr>
            <tr>
                <td class="item_title">
                    是否启用:
                </td>
                <td class="item_input">
                    <input name="IsEnabled" id="Radio1" type="radio" value="@((int)DotNet.SSO.Model.Enum.IsEnabledEnum.Enabled)" checked=checked />启用
                    <input name="IsEnabled" id="Radio2" type="radio"  value="@((int)DotNet.SSO.Model.Enum.IsEnabledEnum.Disabled)" />禁用
                    @Html.ValidationMessageFor(model => model.MaxAmount)
                </td>
            </tr>

            <tr>
                <td class="item_title">
                    单点登录池主域:
                </td>
                <td class="item_input">
                 @Html.DropDownListFor(model => model.MainDomainId, ViewData["MainDomainId"] as SelectList, new { @class = "form-control input-sm" })
                </td>
            </tr>
            <tr>
                <td class="item_title">
                    备注:
                </td>
                <td class="item_input">
                    @Html.TextAreaFor(model => model.ReMark, new { @rows = 3, @class = "form-control", @placeholder = "备注" })
                    @*   @Html.ValidationMessageFor(model=>model.ReMark)*@
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    &nbsp;
                </td>
            </tr>
            <tr>
                <td class="item_title">
                </td>
                <td class="item_input">
                    <button type="submit" class="btn btn-primary btn-sm" style="width: 150px;">
                        保存</button>
                </td>
            </tr>
        </table>
    }
</div>
@section scripts{
    <script type="text/javascript" src="@Url.Content("~/Content/js/ssopool.js")"></script>
}

DotNet.SSO.Portal/Areas/Manager/Views/SSOPool/SSOPoolList.cshtml
@{
    ViewBag.Title = "单点登录池";
    Layout = "~/Views/Shared/_LayoutList.cshtml";
}
@model DotNet.SSO.Model.PagingModel<DotNet.SSO.Model.SSOPool>
@using DotNet.SSO.Portal
<div class="listbox">
    <div class="pagetitle">
        单点登录池管理</div>
    <div class="buttonz">
        <a href="@Url.Content("/Manager/SSOPool/SSOPoolAdd")" class="btn btn-success btn-sm">
            添加单点登录池</a> @* <a href="javascript:;" class="btn btn-danger btn-sm" onclick="delall_user();">批量删除</a>*@
    </div>
    <div class="search_row">
        <div class="form-inline">
            <form action="@Url.Content("/Manager/SSOPool/SSOPoolSearch")" method="post">
            <div class="form-group">
                <label>
                    单点登录池名称：</label>
                <input type="text" class="form-control  input-sm" id="poolName" name="poolName" />
            </div>
            <div class="form-group">
                <label>
                    是否启用：</label>
                @Html.DropDownList("isEnabled", ViewBag.Select as List<SelectListItem>, new { @class = "form-control input-sm" })
            </div>
            <input id="btnSubmit" type="submit" value="搜索" class="btn btn-default  btn-sm" />
            @* <a href="javascript:;" class="btn btn-default  btn-sm">搜索</a>*@
            </form>
        </div>
    </div>
    @{
        string currentUrl = DotNet.SSO.BllUtility.ParamHelper.GetInstance().GetRequestParamWithOutPage();
        int pageIndex = DotNet.Utils.Untility.ConvertFactory.ToInt32(HttpUtility.UrlEncode(Request["page"]), 1);
        <table class="table table-bordered table-condensed">
            <tr>
                <th width="1%">
                    <input type="checkbox" id="checkall" />
                </th>
                <th width="5%">
                    ID
                </th>
                <th width="15%">
                    单点登录池名称
                </th>
                <th width="15%">
                    最大域数量
                </th>
                <th width="15%">
                    是否启用
                </th>
                <th width="20%">
                    单点登录主域Id
                </th>
                <th width="29%">
                    操作
                </th>
            </tr>
            @foreach (var item in Model.Data)
            {
                <tr>
                    <td class="text-center">
                        <input type="checkbox" name="checklist" id="chk_@item.PoolId" value="@item.PoolId" />
                    </td>
                    <td class="text-center">
                        @item.PoolId
                    </td>
                    <td class="text-center">
                        @item.PoolName
                    </td>
                    <td class="text-center">
                        @item.MaxAmount
                    </td>
                    <td class="text-center">
                        @if (item.IsEnabled == (int)DotNet.SSO.Model.Enum.IsEnabledEnum.Enabled)
                        {
                            <a href="javascript:;" onclick="ClosePool(@item.PoolId);">启用</a>
                        }
                        else if (item.IsEnabled == (int)DotNet.SSO.Model.Enum.IsEnabledEnum.Disabled)
                        {
                            <a href="javascript:;" onclick="OpenPool(@item.PoolId);">禁用</a>
                        }
                    </td>
                    <td class="text-center">
                        @item.MainDomainId
                    </td>
                    <td class="text-center">
                        <a href="@Url.Content(string.Format("/Manager/SSOPool/SSOPoolDisplay?poolId={0}", item.PoolId))">
                            查看</a> <a href="@Url.Content(string.Format("/Manager/SSOPool/SSOPoolEdit?poolId={0}", item.PoolId))">
                                编辑</a> <a href="javascript:;"
                            onclick="delpool(@item.PoolId);">删除</a>
                    </td>
                </tr>
            }
        </table>
        @Html.PagingOne(currentUrl, pageIndex, 12, Model.TotalRecord)
    }
</div>
@section scripts{
    <script type="text/javascript" src="@Url.Content("~/Content/js/ssopool.js")"></script>
}