DotNet.SSO.Portal/Areas/Manager/Controllers/DomainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DotNet.SSO.IBll;
using DotNet.SSO.Bll;
using DotNet.SSO.Model.Parameter;
//using DotNet.SSO.IDal;
//using DotNet.SSO.Dal;
using DotNet.SSO.Model.ViewModel;
using DotNet.SSO.Model.Enum;

namespace DotNet.SSO.Portal.Areas.Manager.Controllers
{
    public class DomainController : Controller
    {
        // GET: /Manager/Domain/DomainList
        #region 域管理列表
        [HttpGet]
        public ActionResult DomainList()
        {
            IDomainService domainService = new DomainService();
            DomainParam parameter = new DomainParam()
            {
                PageIndex = DotNet.Utils.Untility.ConvertFactory.ToInt32(HttpUtility.UrlEncode(Request["page"]), 1),
                PageSize = 12,
                IsEnabled = DotNet.Utils.Untility.ConvertFactory.ToInt32(HttpUtility.UrlEncode(Request["isEnabled"]), 0),
                DomainName = HttpUtility.HtmlEncode(Request["domainName"]),
                IsPaging = true,
                DomainCode = HttpUtility.HtmlEncode(Request["domainCode"]),
                DomainLevel = DotNet.Utils.Untility.ConvertFactory.ToInt32(HttpUtility.UrlEncode(Request["domainLevel"]), 0),
                IsSSO = DotNet.Utils.Untility.ConvertFactory.ToInt32(HttpUtility.UrlEncode(Request["isSSO"]), 0),
                DomainUrl = HttpUtility.UrlEncode(Request["domainUrl"])
            };
            var pagingModel = domainService.GetPagingDomain(parameter);

            return View(pagingModel);
        } 
        #endregion

        // GET,POST /Manager/Domain/DomainAdd
        #region 添加域
        [HttpGet]
        public ActionResult DomainAdd()
        {
            List<SelectListItem> selectList = new List<SelectListItem>()
            {
                new SelectListItem(){ Text="一级域名",Value="1",Selected=true },
                new SelectListItem(){ Text="二级域名",Value="2"},
                new SelectListItem(){ Text="三级域名",Value="3" }
            };
            ViewData["DomainLevel"] = selectList;
            List<SelectListItem> poolSelectList = new List<SelectListItem>()
            {
                new SelectListItem(){ Text="请选择",Value="0",Selected=true }
            };
            ISSOPoolService service = new SSOPoolService();
            var poolList = service.GetSSOPoolList();
            foreach (var item in poolList)
            {
                SelectListItem selectItem = new SelectListItem()
                {
                    Text = item.PoolName,
                    Value = item.PoolId.ToString()
                };
                poolSelectList.Add(selectItem);
            }
            ViewData["SSOPoolPoolId"] = poolSelectList;


            return View();
        }
        //添加域,提交
        [HttpPost]
        public ActionResult DomainAdd(DomainAddModel addModel)
        {
            IDomainService service = new DomainService();
            var jsonModel = service.AddDomain(addModel);
            if (jsonModel.Success)
            {
                return Json(new { success = true, msg = "添加成功" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, msg = jsonModel.ErrMsg }, JsonRequestBehavior.AllowGet);
            }
        }


        #endregion

        // GET /Manager/Domain/LoadLevelDomain
        #region 加载某一个级别的所有域
        [HttpGet]
        public ActionResult LoadLevelDomain(int level)
        {
            IDomainService service = new DomainService();
            var domainList = service.GetListDomain(new DomainParam() { DomainLevel=level });
            return Json(domainList, JsonRequestBehavior.AllowGet);
        } 
        #endregion

        // HttpPost: /Manager/Domain/DomainSearch
        #region 域搜索
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult DomainSearch()
        {
            string domainName = HttpUtility.HtmlEncode(Request["domainName"]);
            string isEnabled = HttpUtility.HtmlEncode(Request["isEnabled"]);
            string domainCode= HttpUtility.HtmlEncode(Request["domainCode"]);
            string domainLevel=HttpUtility.HtmlEncode(Request["domainLevel"]);
            string domainUrl=HttpUtility.UrlEncode(Request["domainUrl"]);
            string isSSO = HttpUtility.UrlEncode(Request["isSSO"]);
            return Redirect(string.Format("/Manager/Domain/DomainList?domainName={0}&isEnabled={1}&domainCode={2}&domainLevel={3}&domainUrl={4}&isSSO={5}", domainName, isEnabled, domainCode, domainLevel, domainUrl, isSSO));
        } 
        #endregion

        // POST: /Manager/Domain/ChangeDomainEnabled
        #region 开启或者关闭域名
        [HttpPost]
        public ActionResult ChangeDomainEnabled()
        {
            int domainId = DotNet.Utils.Untility.ConvertFactory.ToInt32(HttpUtility.HtmlEncode(Request["domainId"]), 0);
            int isEnabled = DotNet.Utils.Untility.ConvertFactory.ToInt32(HttpUtility.HtmlEncode(Request["isEnabled"]), (int)IsEnabledEnum.Enabled);
            IDomainService service = new DomainService();
            var jsonModel = service.ChangeDomainEnabled(domainId, isEnabled);
            if (jsonModel.Success)
            {
                return Json(new { success = true, msg = "操作成功" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = true, msg = jsonModel.ErrMsg }, JsonRequestBehavior.AllowGet);
            }
        }  
        #endregion

        // POST: /Manager/Domain/DomainDelete
        #region 删除域
        [HttpPost]
        public ActionResult DomainDelete(int domainId)
        {
            IDomainService service = new DomainService();
            var jsonModel = service.DeleteDomain(domainId);
            if (jsonModel.Success)
            {
                return Json(new { success = true, msg = "删除成功" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, msg = jsonModel.ErrMsg }, JsonRequestBehavior.AllowGet);
            }
        } 
        #endregion

        //GET :/Manager/Domain/DomainDisplay
        #region 显示域的详情
        [HttpGet]
        public ActionResult DomainDisplay()
        {
            int domainId = DotNet.Utils.Untility.ConvertFactory.ToInt32(Request["domainId"], 0);
            IDomainService service = new DomainService();
            var domain = service.GetDomain(new DomainSingleParam() { DomainId=domainId });
            return View(domain);
        }
        #endregion

        //GET,POST :/Manager/Domain/DomainEdit
        #region 修改域信息
        [HttpGet]
        public ActionResult DomainEdit(int domainId)
        {
            IDomainService service = new DomainService();
            var model = service.GetEditModel(domainId);
            //域级别select
            List<SelectListItem> levelSelectList = new List<SelectListItem>()
            {
                new SelectListItem(){ Text="一级域名",Value="1",Selected=(model.DomainLevel==1)},
                new SelectListItem(){ Text="二级域名",Value="2",Selected=(model.DomainLevel==2)},
                new SelectListItem(){ Text="三级域名",Value="3",Selected=(model.DomainLevel==3)},
            };
            //上级域名select
            List<SelectListItem> parentSelectList = new List<SelectListItem>()
            {
                new SelectListItem(){ Text="无",Value="0",Selected=(model.ParentDomainId==0)}
            };
            if (model.DomainLevel > 1)
            {
                var domainList = service.GetListDomain(new DomainParam() { DomainLevel = model.DomainLevel - 1 });
                foreach (var domain in domainList)
                {
                    SelectListItem item = new SelectListItem()
                    {
                        Text = domain.DomainName,
                        Value = domain.DomainId.ToString(),
                        Selected = (model.ParentDomainId == domain.DomainId)
                    };
                    parentSelectList.Add(item);
                }
            }
            //单点登录池的select
            List<SelectListItem> poolSelectList = new List<SelectListItem>();
            ISSOPoolService ssoPoolService = new SSOPoolService();
            var poolList = ssoPoolService.GetSSOPoolList();
            foreach (var pool in poolList)
            {
                SelectListItem item = new SelectListItem()
                {
                    Text=pool.PoolName,
                    Value=pool.PoolId.ToString(),
                    Selected=(model.SSOPoolPoolId==pool.PoolId)
                };
                poolSelectList.Add(item);
            }

            this.ViewData["DomainLevel"] = levelSelectList;
            this.ViewData["ParentDomainId"] = parentSelectList;
            this.ViewData["SSOPoolPoolId"] = poolSelectList;
            return View(model);
        }

        [HttpPost]
        public ActionResult DomainEdit(DomainEditModel editModel)
        {
            IDomainService service = new DomainService();
            var jsonModel = service.EditDomain(editModel);
            if (jsonModel.Success)
            {
                return Json(new { success = true, msg = "修改成功" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, msg = jsonModel.ErrMsg }, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion


    }
}

DotNet.SSO.Portal/Areas/Manager/Views/Domain/DomainAdd.cshtml
@model DotNet.SSO.Model.ViewModel.DomainAddModel
@{
    ViewBag.Title = "添加域";
    Layout = "~/Views/Shared/_LayoutAdd.cshtml";
}
<div class="listbox">
    <div class="pagetitle">
        添加域 <a href="@Url.Content("/Manager/Domain/DomainList")">>>返回列表</a>
    </div>
   @* startLoading('正在加载')*@
    @using (Ajax.BeginForm("DomainAdd", "Domain", new { }, new AjaxOptions() { HttpMethod = "Post", OnBegin = "startLoading('正在提交')", OnSuccess = "AfterDomainAdd" }, new { id = "DomainAdd" }))
    { 
        <table class="table table-bordered table-condensed">
            <tr>
                <td colspan="2">
                    添加域
                </td>
            </tr>
            <tr>
                <td class="item_title">
                    域名称:
                </td>
                <td class="item_input">
                    @Html.TextBoxFor(model => model.DomainName, new { @class = "form-control input-sm", @placeholder = "域名称" })
                    @Html.ValidationMessageFor(model => model.DomainName)
                </td>
            </tr>
              <tr>
                <td class="item_title">
                    域密码:
                </td>
                <td class="item_input">
                    @Html.PasswordFor(model => model.DomainPassword, new { @class = "form-control input-sm", @placeholder = "域密码" })
                    @Html.ValidationMessageFor(model => model.DomainPassword)
                </td>
            </tr>
            <tr>
                <td class="item_title">
                    域网址:
                </td>
                <td class="item_input">
                    @Html.TextBoxFor(model => model.DomainUrl, new { @class = "form-control input-sm", @placeholder = "域网址" })
                  @Html.ValidationMessageFor(model => model.DomainUrl)
                </td>
            </tr>
            <tr>
                <td class="item_title">
                    域级别:
                </td>
                <td class="item_input">
                    @Html.DropDownListFor(model => model.DomainLevel, ViewData["DomainLevel"] as List<SelectListItem>, new { })
                    @Html.ValidationMessageFor(model => model.DomainUrl)
                </td>
            </tr>
             <tr id="parent_domain">
                <td class="item_title">
                    上一级域:
                </td>
                <td class="item_input">
                    <select id="ParentDomainId" name="ParentDomainId">
                    <option value="0" selected="selected">无</option>
                    </select>
                </td>
            </tr>

            <tr>
                <td class="item_title">
                    是否启用:
                </td>
                <td class="item_input">
                    <input name="IsEnabled" id="rad_enabled1" type="radio" value="@((int)DotNet.SSO.Model.Enum.IsEnabledEnum.Enabled)" checked=checked />启用
                    <input name="IsEnabled" id="rad_enabled2" type="radio"  value="@((int)DotNet.SSO.Model.Enum.IsEnabledEnum.Disabled)" />禁用
                    @Html.ValidationMessageFor(model => model.IsEnabled)
                </td>
            </tr>
            <tr>
                <td class="item_title">
                    是否单点登录:
                </td>
                <td class="item_input">
                    <input name="IsSSO" id="ssoRadio1" type="radio" value="@((int)DotNet.SSO.Model.Enum.IsSSOEnum.SSO)" checked=checked />启用单点登录
                    <input name="IsSSO" id="ssoRadio2" type="radio"  value="@((int)DotNet.SSO.Model.Enum.IsSSOEnum.Single)" />不使用单点登录
                    @Html.ValidationMessageFor(model => model.IsEnabled)
                </td>
            </tr>
            <tr >
                <td class="item_title">
                    单点登录网址:
                </td>
                <td class="item_input">
                    @Html.TextBoxFor(model => model.SSOUrl, new { @class = "form-control input-sm", @placeholder = "域网址" })
                    @Html.ValidationMessageFor(model => model.SSOUrl)
                </td>
            </tr>
            <tr id="tr_ssopool">
                <td class="item_title">
                    单点登录池:
                </td>
                <td class="item_input">
                   @Html.DropDownListFor(model => model.SSOPoolPoolId, ViewData["SSOPoolPoolId"] as List<SelectListItem>, new { })
                    @Html.ValidationMessageFor(model => model.SSOPoolPoolId)
                </td>
            </tr>
              <tr>
                <td class="item_title">
                    Cookie存放的域名:
                </td>
                <td class="item_input">
                    @Html.TextBoxFor(model => model.CookieDomain, new { @class = "form-control input-sm", @placeholder = "域网址" })
                    @Html.ValidationMessageFor(model => model.CookieDomain)
                </td>
            </tr>
            <tr>
                <td class="item_title">
                    备注:
                </td>
                <td class="item_input">
                    @Html.TextAreaFor(model => model.ReMark, new { @rows = 3, @class = "form-control", @placeholder = "备注" })
                    @*   @Html.ValidationMessageFor(model=>model.ReMark)*@
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    &nbsp;
                </td>
            </tr>
            <tr>
                <td class="item_title">
                </td>
                <td class="item_input">
                    <button type="submit" class="btn btn-primary btn-sm" style="width: 150px;">
                        保存</button>
                </td>
            </tr>
        </table>
    }
</div>
@section scripts{
    <script type="text/javascript" src="@Url.Content("~/Content/js/domain.js")"></script>
}

DotNet.SSO.Portal/Areas/Manager/Views/Domain/DomainDisplay.cshtml
@model DotNet.SSO.Model.Domain
@{
    ViewBag.Title = "域详情";
    Layout = "~/Views/Shared/_LayoutDisplay.cshtml";
}
<div class="listbox">
    <div class="pagetitle">
        域详情 <a href="@Url.Content("/Manager/Domain/DomainList")">>>返回列表</a>
    </div>
    <table class="table table-bordered table-condensed">
        <tr>
            <td colspan="2">
                域详情
            </td>
        </tr>
        <tr>
            <td class="item_title">
                域名称:
            </td>
            <td class="item_input">
                @Model.DomainName
            </td>
        </tr>
        <tr>
            <td class="item_title">
                标识码:
            </td>
            <td class="item_input">
                @Model.DomainCode
            </td>
        </tr>
        <tr>
            <td class="item_title">
                域密钥:
            </td>
            <td class="item_input">
                @Model.DomainKey
            </td>
        </tr>
          <tr>
            <td class="item_title">
                域的密码:
            </td>
            <td class="item_input">
                @Model.DomainPassword
            </td>
        </tr>
        <tr>
            <td class="item_title">
                域地址:
            </td>
            <td class="item_input">
                @Model.DomainUrl
            </td>
        </tr>
        <tr>
            <td class="item_title">
                域级别:
            </td>
            <td class="item_input">
                @{
                    switch (Model.DomainLevel)
                    {
                        case 1:<span>一级域名</span>
                            break;
                        case 2:<span>二级域名</span>
                            break;
                        case 3:<span>三级域名</span>
                            break;
                        default: break;

                    }
                }
            </td>
        </tr>
        <tr>
            <td class="item_title">
                上级域:
            </td>
            <td class="item_input">
                @{
                    <span>ID:@Model.ParentDomainId</span>
                    if (Model.ParentDomainId > 0)
                    {
                    
                    <a href="@Url.Content(string.Format("/Manager/Domain/DomainDisplay?domainId={0}", Model.ParentDomainId))">
                        查看</a> 
                    }
                }
            </td>
        </tr>
        <tr>
            <td class="item_title">
                是否启用:
            </td>
            <td class="item_input">
                @if (Model.IsEnabled == (int)DotNet.SSO.Model.Enum.IsEnabledEnum.Enabled)
                {
                    <span>启用</span> 
                }
                else
                { 
                    <span>禁用</span> 
                }
            </td>
        </tr>
        <tr>
            <td class="item_title">
                是否单点登录:
            </td>
            <td class="item_input">
                @if (Model.IsSSO == (int)DotNet.SSO.Model.Enum.IsSSOEnum.SSO)
                {
                    <span>单点登录</span> 
                }
                else
                { 
                    <span>非单点登录</span> 
                }
            </td>
        </tr>
        <tr>
            <td class="item_title">
                单点登录地址:
            </td>
            <td class="item_input">
                @Model.SSOUrl
            </td>
        </tr>
           <tr>
            <td class="item_title">
                Cookie存放地址:
            </td>
            <td class="item_input">
                @Model.CookieDomain
            </td>
        </tr>
            <tr>
            <td class="item_title">
                所在单点登录池:
            </td>
            <td class="item_input">
                <a href="@Url.Content(string.Format("/Manager/SSOPool/SSOPoolDisplay?poolId={0}",Model.SSOPoolPoolId))">@Model.Pool.PoolName</a>
            </td>
        </tr>
        <tr>
            <td class="item_title">
                备注:
            </td>
            <td class="item_input">
                @Model.ReMark
            </td>
        </tr>

    </table>
</div>
@section scripts{
    <script type="text/javascript" src="@Url.Content("~/Content/js/ssopool.js")"></script>
}

DotNet.SSO.Portal/Areas/Manager/Views/Domain/DomainEdit.cshtml
@model DotNet.SSO.Model.ViewModel.DomainEditModel
@{
    ViewBag.Title = "修改域实体";
    Layout = "~/Views/Shared/_LayoutEdit.cshtml";
}
<div class="listbox">
    <div class="pagetitle">
        修改域 <a href="@Url.Content("/Manager/Domain/DomainList")">>>返回列表</a>
    </div>
    @* startLoading('正在加载')*@
    @using (Ajax.BeginForm("DomainEdit", "Domain", new { }, new AjaxOptions() { HttpMethod = "Post", OnBegin = "startLoading('正在提交')", OnSuccess = "AfterDomainEdit" }, new { id = "DomainEdit" }))
    { 
        @Html.HiddenFor(model => model.DomainId)
        <table class="table table-bordered table-condensed">
            <tr>
                <td colspan="2">
                    修改域
                </td>
            </tr>
            <tr>
                <td class="item_title">
                    域名称:
                </td>
                <td class="item_input">
                    @Html.TextBoxFor(model => model.DomainName, new { @class = "form-control input-sm", @placeholder = "域名称" })
                    @Html.ValidationMessageFor(model => model.DomainName)
                </td>
            </tr>
            @*      <tr>
                <td class="item_title">
                    域密码:
                </td>
                <td class="item_input">
                    @Html.TextBoxFor(model => model.DomainPassword, new { @class = "form-control input-sm", @placeholder = "域密码", @autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.DomainPassword)
                </td>
            </tr>*@
            <tr>
                <td class="item_title">
                    域网址:
                </td>
                <td class="item_input">
                    @Html.TextBoxFor(model => model.DomainUrl, new { @class = "form-control input-sm", @placeholder = "域网址" })
                    @Html.ValidationMessageFor(model => model.DomainUrl)
                </td>
            </tr>
            <tr>
                <td class="item_title">
                    域级别:
                </td>
                <td class="item_input">
                    @Html.DropDownListFor(model => model.DomainLevel, ViewData["DomainLevel"] as SelectList, new { @class = "form-control input-sm" })
                    @Html.ValidationMessageFor(model => model.DomainLevel)
                </td>
            </tr>
            <tr id="parent_domain">
                <td class="item_title">
                    上一级域:
                </td>
                <td class="item_input">
                    @Html.DropDownListFor(model => model.ParentDomainId, ViewData["ParentDomainId"] as SelectList, new { @class = "form-control input-sm" })
                    @Html.ValidationMessageFor(model => model.ParentDomainId)
                </td>
            </tr>
            <tr>
                <td class="item_title">
                    是否启用:
                </td>
                <td class="item_input">
                    @if (Model.IsEnabled == (int)DotNet.SSO.Model.Enum.IsEnabledEnum.Enabled)
                    {
                        <input name="IsEnabled" id="rad_enabled1" type="radio" value="@((int)DotNet.SSO.Model.Enum.IsEnabledEnum.Enabled)" checked=checked /><span>启用</span>
                        <input name="IsEnabled" id="rad_enabled2" type="radio"  value="@((int)DotNet.SSO.Model.Enum.IsEnabledEnum.Disabled)" /><span>禁用</span>
                    }
                    else
                    {
                        <input name="IsEnabled" id="rad_enabled1" type="radio" value="@((int)DotNet.SSO.Model.Enum.IsEnabledEnum.Enabled)"  />
                        <span>启用</span>
                        <input name="IsEnabled" id="rad_enabled2" type="radio"  value="@((int)DotNet.SSO.Model.Enum.IsEnabledEnum.Disabled)" checked=checked /><span>禁用</span>
                    }
                    @Html.ValidationMessageFor(model => model.IsEnabled)
                </td>
            </tr>
            <tr>
                <td class="item_title">
                    是否单点登录:
                </td>
                <td class="item_input">
                    <input name="IsSSO" id="ssoRadio1" type="radio" value="@((int)DotNet.SSO.Model.Enum.IsSSOEnum.SSO)" checked=checked />启用单点登录
                    <input name="IsSSO" id="ssoRadio2" type="radio"  value="@((int)DotNet.SSO.Model.Enum.IsSSOEnum.Single)" />不使用单点登录
                    @Html.ValidationMessageFor(model => model.IsEnabled)
                </td>
            </tr>
            <tr>
                <td class="item_title">
                    单点登录网址:
                </td>
                <td class="item_input">
                    @Html.TextBoxFor(model => model.SSOUrl, new { @class = "form-control input-sm", @placeholder = "域网址" })
                    @Html.ValidationMessageFor(model => model.SSOUrl)
                </td>
            </tr>
            <tr id="tr_ssopool">
                <td class="item_title">
                    单点登录池:
                </td>
                <td class="item_input">
                    @Html.DropDownListFor(model => model.SSOPoolPoolId, ViewData["SSOPoolPoolId"] as SelectList, new { @class = "form-control input-sm" })
                </td>
            </tr>
            <tr>
                <td class="item_title">
                    Cookie存放的域名:
                </td>
                <td class="item_input">
                    @Html.TextBoxFor(model => model.CookieDomain, new { @class = "form-control input-sm", @placeholder = "域网址" })
                    @Html.ValidationMessageFor(model => model.CookieDomain)
                </td>
            </tr>
            <tr>
                <td class="item_title">
                    备注:
                </td>
                <td class="item_input">
                    @Html.TextAreaFor(model => model.ReMark, new { @rows = 3, @class = "form-control", @placeholder = "备注" })
                    @*   @Html.ValidationMessageFor(model=>model.ReMark)*@
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    &nbsp;
                </td>
            </tr>
            <tr>
                <td class="item_title">
                </td>
                <td class="item_input">
                    <button type="submit" class="btn btn-primary btn-sm" style="width: 150px;">
                        保存</button>
                </td>
            </tr>
        </table>
    }
</div>
@section scripts{
    <script type="text/javascript" src="@Url.Content("~/Content/js/domain.js")"></script>
}